---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  labels:
    app: mongodb-svc
spec:
  ports:
    - name: mongodb-sts-vol
      port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32000
  selector:
    app: mongodb-sts-vol
  type: NodePort
